name: Python Tests and Revert on Fail

on: [push]

jobs:
  test_and_revert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        id: tests
        run: |
          pytest test.py
      - name: Revert changes if tests fail
        if: failure()
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git revert HEAD --no-edit
          git push origin HEAD